# Nome do Workflow
name: DevSecOps Pipeline

# Evento que irá acionar a pipeline
on: 
  push:
    branches:
      - develop

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name:  Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
