# Nome do Workflow
name: DevSecOps Pipeline

# Evento que irá acionar a pipeline
on: 
  push:
    branches:
      - develop

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name:  Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm run test:headless

      - name: Build
        run: npm run build:prod
        
      - name: Deploy
        if: success()
        run: aws s3 sync ./dist s3://our-finances-app
